# Generated by Django 5.2.8 on 2025-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionmessage',
            name='detaisls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
