# Generated by Django 5.2.8 on 2025-11-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickes', '0002_solutionmessage_detaisls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionmessage',
            old_name='detaisls',
            new_name='details',
        ),
    ]
